# Generated by Django 6.0 on 2025-12-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_labelbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltemplatefield',
            name='bg_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='font_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='font_italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='font_size',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='font_underline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='is_static',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='shape_color',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='shape_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('RECT', 'Rectangle'), ('CIRCLE', 'Circle'), ('STAR', 'Star'), ('TRIANGLE', 'Triangle')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='static_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
