# Generated by Django 6.0 on 2025-12-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_labeltemplatefield_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltemplate',
            name='canvas_bg_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='labeltemplatefield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE_URL', 'Image URL'), ('PRICE', 'Price'), ('SERIAL', 'Serial Number'), ('BARCODE', 'Barcode'), ('QRCODE', 'QR Code'), ('STATIC_TEXT', 'Static Text'), ('SHAPE', 'Shape')], default='TEXT', max_length=20),
        ),
    ]
