# Generated by Django 6.0 on 2025-12-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_labeltemplate_canvas_bg_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeltemplate',
            name='canvas_bg_color',
        ),
        migrations.RemoveField(
            model_name='labeltemplatefield',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='labeltemplatefield',
            name='font_bold',
        ),
        migrations.RemoveField(
            model_name='labeltemplatefield',
            name='font_italic',
        ),
        migrations.RemoveField(
            model_name='labeltemplatefield',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='labeltemplatefield',
            name='font_underline',
        ),
        migrations.RemoveField(
            model_name='labeltemplatefield',
            name='is_static',
        ),
        migrations.RemoveField(
            model_name='labeltemplatefield',
            name='shape_color',
        ),
        migrations.RemoveField(
            model_name='labeltemplatefield',
            name='shape_type',
        ),
        migrations.RemoveField(
            model_name='labeltemplatefield',
            name='static_text',
        ),
        migrations.RemoveField(
            model_name='labeltemplatefield',
            name='text_color',
        ),
        migrations.AlterField(
            model_name='labeltemplatefield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE_URL', 'Image URL'), ('PRICE', 'Price'), ('SERIAL', 'Serial Number'), ('BARCODE', 'Barcode'), ('QRCODE', 'QR Code')], default='TEXT', max_length=20),
        ),
    ]
