# Generated by Django 6.0 on 2026-01-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_remove_labeltemplate_canvas_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltemplate',
            name='canvas_bg_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='bg_color',
            field=models.CharField(blank=True, default='transparent', max_length=20),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='font_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='font_family',
            field=models.CharField(blank=True, default='Inter', max_length=50),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='font_italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='font_size',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='font_underline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='shape_color',
            field=models.CharField(blank=True, default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='shape_type',
            field=models.CharField(blank=True, choices=[('RECT', 'Rectangle'), ('CIRCLE', 'Circle'), ('TRIANGLE', 'Triangle'), ('STAR', 'Star')], default='RECT', max_length=20),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='show_label',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='text_color',
            field=models.CharField(blank=True, default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='labeltemplatefield',
            name='z_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='globaltemplatefield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE_URL', 'Image URL'), ('PRICE', 'Price'), ('SERIAL', 'Serial Number'), ('BARCODE', 'Barcode'), ('QRCODE', 'QR Code'), ('STATIC_TEXT', 'Static Text'), ('SHAPE', 'Shape')], max_length=20),
        ),
        migrations.AlterField(
            model_name='labeltemplatefield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE_URL', 'Image URL'), ('PRICE', 'Price'), ('SERIAL', 'Serial Number'), ('BARCODE', 'Barcode'), ('QRCODE', 'QR Code'), ('STATIC_TEXT', 'Static Text'), ('SHAPE', 'Shape')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspacefield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE_URL', 'Image URL'), ('PRICE', 'Price'), ('SERIAL', 'Serial Number'), ('BARCODE', 'Barcode'), ('QRCODE', 'QR Code'), ('STATIC_TEXT', 'Static Text'), ('SHAPE', 'Shape')], max_length=20),
        ),
    ]
