# Generated by Django 6.0 on 2026-01-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_labeltemplate_canvas_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltemplate',
            name='layout_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='print_defaults',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='labeltemplatefield',
            unique_together={('template', 'key')},
        ),
    ]
