# Generated by Django 6.0 on 2026-01-18 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_labeltemplate_layout_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(default=1)),
                ('ean_code', models.CharField(max_length=64)),
                ('gs1_code', models.CharField(blank=True, default='', max_length=64)),
                ('field_values', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workspaces.labelbatch')),
            ],
            options={
                'ordering': ['row_index', 'id'],
            },
        ),
    ]
