# Generated by Django 6.0 on 2026-01-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_labelbatchitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelbatch',
            name='ean_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='labelbatch',
            name='gs1_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
