# Generated by Django 6.0 on 2026-01-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_alter_labelbatch_ean_code_alter_labelbatch_gs1_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelbatchitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
