# Generated by Django 6.0 on 2026-01-20 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_user_code'),
        ('billing', '0003_superplanrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgLimitOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_limit_override', models.PositiveIntegerField(blank=True, null=True)),
                ('template_limit_override', models.PositiveIntegerField(blank=True, null=True)),
                ('labels_per_period_override', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limit_override', to='accounts.org')),
            ],
        ),
    ]
