# Generated by Django 6.0 on 2026-01-21 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_orglimitoverride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='superplanrequest',
            old_name='decided_at',
            new_name='approved_at',
        ),
        migrations.RemoveField(
            model_name='superplanrequest',
            name='decided_by',
        ),
        migrations.RemoveField(
            model_name='superplanrequest',
            name='note',
        ),
        migrations.AddField(
            model_name='superplanrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_super_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
