# Generated by Django 6.0 on 2026-01-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_rename_decided_at_superplanrequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentevent',
            name='provider_order_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='provider_signature',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='provider',
            field=models.CharField(default='RAZORPAY', max_length=32),
        ),
    ]
