# Generated by Django 6.0 on 2026-03-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_paymentevent_provider_order_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planversion',
            options={'ordering': ['plan__code', 'currency', '-version']},
        ),
        migrations.AlterUniqueTogether(
            name='planversion',
            unique_together={('plan', 'currency', 'version')},
        ),
    ]
