# Generated by Django 6.0 on 2026-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_planversion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planversion',
            options={'ordering': ['plan__code', 'currency', 'billing_cycle', '-version']},
        ),
        migrations.AlterUniqueTogether(
            name='planversion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='planversion',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=10),
        ),
        migrations.AddField(
            model_name='planversion',
            name='period_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterUniqueTogether(
            name='planversion',
            unique_together={('plan', 'currency', 'billing_cycle', 'version')},
        ),
    ]
