# Generated by Django 6.0 on 2026-01-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BLOG', 'Blog'), ('VIDEO', 'Video')], default='BLOG', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('meta_title', models.CharField(blank=True, default='', max_length=60)),
                ('meta_description', models.CharField(blank=True, default='', max_length=160)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='cms/previews/')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='cms/og/')),
                ('blog_html', models.TextField(blank=True, default='')),
                ('video_description', models.TextField(blank=True, default='')),
                ('youtube_embed_html', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
