# Generated by Django 6.0 on 2026-03-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_is_verified_user_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_reminder_stage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
